echo Switching to Root user...
sudo su
echo Updating the image on `date`...
yum update -y
echo Installing Docker on `date`...
yum install docker -y 
docker --version
systemctl start docker

echo Installing git on `date`...
yum install git -y 
git --version

git clone 
echo Setting build environment variable on `date`...
REPOSITORY_URI=821438830100.dkr.ecr.us-east-1.amazonaws.com/custom-docker-imagetag
COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
IMAGE_TAG=${COMMIT_HASH:=latest}
echo Logging in to Amazon ECR...
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 821438830100.dkr.ecr.us-east-1.amazonaws.com
echo Build started on `date`...
echo Building the Docker image...          
# docker build -t $REPOSITORY_URI:latest .
# docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
docker build -t $REPOSITORY_URI:$IMAGE_TAG .

echo Post-Build completed on `date`...
# docker push $REPOSITORY_URI:latest
docker push $REPOSITORY_URI:$IMAGE_TAG
echo CodeBuild completed on `date`
echo Updating the SSM imageTag parameter...
aws ssm put-parameter --name imageTag --value $IMAGE_TAG --type String --overwrite
echo Updating SSM imageTag parameter done on `date` !!!...
